"""Email and Mobile Validators.

Revision ID: aafd25740a63
Revises: a1d1c270f913
Create Date: 2025-03-10 17:08:33.836241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafd25740a63'
down_revision: Union[str, None] = 'a1d1c270f913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customermaster', ['email'])
    op.create_unique_constraint(None, 'customermaster', ['alternate_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customermaster', type_='unique')
    op.drop_constraint(None, 'customermaster', type_='unique')
    # ### end Alembic commands ###
